### ISSUE TITLE
Test & Release

### ISSUE THREAD

**Issue by luke-** [humhub/auth-linkedin#1]

**Comment by serh-mosk** [comment]
To check the operation of this module, I need Client ID and Client secret, which can be obtained only by creating an application in the https://developer.linkedin.com/ cabinet. Can you provide them to me or do I need to create a test LinkedIn account?

**Comment by luke-** [comment]
@yuriimaz Would be great if you can create a test linked in account

**Comment by serh-mosk** [comment]
I created a test configuration for the project on LinkedIn and checked the operation of the authorization module.
Since a problem was detected with the registration of a new user in the event of an attempt to authorize using LinkedIn Auth, I made the appropriate changes in the registration class of the main project and created a pull-request with these changes https://github.com/humhub/humhub/pull/6244. Please check that everything is correct and let me know if anything needs to be corrected.

**Comment by luke-** [comment]
@yuriimaz Thanks, I have already replied to the PR in the main project. Please try to make the changes only in the AuthClient of the LinkedIn project.

**Comment by serh-mosk** [comment]
I've made changes to the module, but I can't create a branch and commit to it to prepare a pull request, because I don't have permission to do so. @luke- Can you check if editing rights are enabled for my account?

**Comment by luke-** [comment]
@yuriimaz Please try it again
